version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    image: ws_5_db_image
    container_name: usersdb5
  standalone:
    build:
      context: ./standalone
    image: ws_5_standalone_image
    container_name: standalone5
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:8080
      - 8000:8000
